name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  gsheets: ^0.5.0
  intl: ^0.19.0
  http: ^1.2.1
  # shelf: ^1.4.1
  # shelf_router: ^1.1.4
  cron: ^0.6.0
  # timezone: ^0.9.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
